### ISSUE TITLE
CentOS requirements

### ISSUE THREAD

**Issue by exente** [ecstatic-nobel/osweep#3]
Although is not an issue itself, I apologize but I don't know other place to share this info for the people after do an intallation in a different Linux Platform.

Prerequites:
Also is required Python-devel package
If you are newbie on CentOS, keep in mind you need also to install "epel-release" and python-pip packages too

Considerations:
When you clone using git, is not required to move the folder from owseep-master to osweep as it is beign downloaded as osweep
After each update, installation or any change review and change the owner of all files on the splunk intallation (solves initial issues)
Most of the issues will come from the Splunk configuration rather from an app configuration or deployment, so it's useful to check the splunk log file on [splunk_installation_folder]/var/log/splunk/ (mainly splunkd.log)

**Comment by exente** [comment]
Tested everything and works on CentOS 7.6.1810 (Core)

**Comment by ecstatic-nobel** [comment]
@exente Thanks again for the suggestions! If you want, I created a team on Keybase called osweep for collaboration. Creating issues on GitHub works as well since it makes the information readily available.

I'll spin up a CentOS VM today to test the prerequisites you mentioned and then place it in the [wiki](https://github.com/leunammejii/osweep/wiki).

For now, the path should be needed since the code is referencing the absolute path to the lookup tables. I'll reopen this issue to test using the relative path instead. That "should" work. 
![a](https://user-images.githubusercontent.com/12433311/50294334-a4759500-0443-11e9-8e56-0cf7dcc62cf8.png)

I'll add the other considerations to the wiki under [Troubleshooting](https://github.com/leunammejii/osweep/wiki/Troubleshooting).

**Comment by ecstatic-nobel** [comment]
Considerations 2 and 3 added.

![a](https://user-images.githubusercontent.com/12433311/50297284-72b3fc80-044a-11e9-9065-00202156f6d0.png)

**Comment by ecstatic-nobel** [comment]
Recommended prerequisites have been tested for CentOS 7+ and added to the wiki. I had to install `gcc` to get the Pip packages to build.

![a](https://user-images.githubusercontent.com/12433311/50315353-719dc200-0480-11e9-87ea-023ac4750f05.png)

**Comment by ecstatic-nobel** [comment]
The command on the Setup page in the wiki has been updated:
- If Git is not installed, then it will run wget
- If the directory osweep does not exists, it will unzip the downloaded file, rename the directory, and hide the zip file

**Comment by ecstatic-nobel** [comment]
A recommended hardware section will be built later but this is the minimum hardware I needed for CentOS:

![a](https://user-images.githubusercontent.com/12433311/50316648-829d0200-0485-11e9-9a27-d5515392458a.png)

**Comment by ecstatic-nobel** [comment]
Release v1.5.3 (`commit 8d183485dc90161a2b6c0ba579ed0257c5d2743a`) has been pushed to solve any non-default installation path issues. The setup commands found in the wiki should solve any absolute path issues.
